/**
 * @fileoverview Magic: The Gathering creature names
 * Used as default operator/username suggestions in HackerHero.
 * These are all creature card names from the official M:TG universe (English).
 * @module magic-names
 */

/**
 * A curated list of memorable Magic: The Gathering creature names.
 * New names can be appended to this array without breaking anything.
 * @type {string[]}
 */
export const MAGIC_CREATURES = [
  // ── A ──────────────────────────────────────────────────────────────────
  'Adanto Vanguard',
  'Adarkar Valkyrie',
  'Adeliz',
  'Akroma',
  'Ambassador Laquatus',
  'Anafenza',
  'Anger',
  'Arcanis the Omnipotent',
  'Archon of Cruelty',
  'Ashen Rider',
  'Ashenmoor Liege',
  'Atarka',
  'Atraxa',
  'Aurelia',
  'Avacyn',
  'Avenger of Zendikar',
  'Azami',
  'Azusa',
  // ── B ──────────────────────────────────────────────────────────────────
  'Balefire Dragon',
  'Ball Lightning',
  'Baneslayer Angel',
  'Basandra',
  'Bladewing the Risen',
  'Bloodbraid Elf',
  'Bloodghast',
  'Blood Artist',
  'Bogardan Hellkite',
  'Borborygmos Enraged',
  'Brago',
  'Braids',
  'Bruna',
  'Burnished Hart',
  // ── C ──────────────────────────────────────────────────────────────────
  'Carnage Tyrant',
  'Champion of the Parish',
  'Chandra\'s Phoenix',
  'Child of Alara',
  'Chromium',
  'Clever Impersonator',
  'Coiling Oracle',
  'Consecrated Sphinx',
  'Copperline Gorge',
  'Craterhoof Behemoth',
  'Cromat',
  'Cruel Ultimatum',
  // ── D ──────────────────────────────────────────────────────────────────
  'Dark Confidant',
  'Deathrite Shaman',
  'Delver of Secrets',
  'Demon of Death\'s Gate',
  'Desolation Angel',
  'Doomgape',
  'Doran the Siege Tower',
  'Dragonlord Dromoka',
  'Dragonlord Ojutai',
  'Drana',
  'Dread Shade',
  'Dreamborn Muse',
  'Drogskol Captain',
  'Dungrove Elder',
  // ── E ──────────────────────────────────────────────────────────────────
  'Edgar Markov',
  'Edric',
  'Elderscale Wurm',
  'Elenda',
  'Elesh Norn',
  'Emeria Angel',
  'Emrakul',
  'Endrek Sahr',
  'Erebos',
  'Eternal Witness',
  'Etrata',
  'Exava',
  'Ezuri',
  // ── F ──────────────────────────────────────────────────────────────────
  'Falkenrath Aristocrat',
  'Fauna Shaman',
  'Feather the Redeemed',
  'Felidar Sovereign',
  'Fiend Hunter',
  'Fleecemane Lion',
  'Fblthp',
  'Forgotten Ancient',
  'Freyalise',
  // ── G ──────────────────────────────────────────────────────────────────
  'Gaddock Teeg',
  'Gallia of the Endless Dance',
  'Garruk\'s Packleader',
  'Geist of Saint Traft',
  'Ghalta',
  'Gisela',
  'Glen Elendra Archmage',
  'Glorybringer',
  'God-Eternal Kefnet',
  'Gonti',
  'Grand Arbiter Augustin',
  'Gravecrawler',
  'Gray Merchant of Asphodel',
  'Grim Flayer',
  'Grimgrin',
  'Griselbrand',
  'Gurmag Angler',
  // ── H ──────────────────────────────────────────────────────────────────
  'Hakim Loreweaver',
  'Hamletback Goliath',
  'Hapatra',
  'Heirloom Blade',
  'Hellkite Charger',
  'Hellkite Overlord',
  'Hellrider',
  'Herald of Anguish',
  'Hissing Quagmire',
  'Horizon Canopy',
  'Huntmaster of the Fells',
  'Hydroid Krasis',
  // ── I ──────────────────────────────────────────────────────────────────
  'Icefall Regent',
  'Impervious Greatwurm',
  'Inferno Titan',
  'Ink-Eyes',
  'Iona',
  'Iroas',
  'Isamaru',
  'Ishkanah',
  // ── J ──────────────────────────────────────────────────────────────────
  'Jace\'s Phantasm',
  'Jazal Goldmane',
  'Jenara',
  'Jin-Gitaxias',
  'Joiner Adept',
  'Judith',
  // ── K ──────────────────────────────────────────────────────────────────
  'Kaalia',
  'Kalitas',
  'Karlov',
  'Karona',
  'Karrthus',
  'Kemba',
  'Keranos',
  'Kess',
  'Kiki-Jiki',
  'Kinnan',
  'Kira',
  'Knight of the Reliquary',
  'Kolaghan',
  'Kokusho',
  'Korvold',
  'Kozilek',
  'Krenko',
  'Kroxa',
  'Kumena',
  'Kytheon',
  // ── L ──────────────────────────────────────────────────────────────────
  'Lazav',
  'Leovold',
  'Lightning Greaves',
  'Linvala',
  'Llanowar Elves',
  'Lord of Atlantis',
  'Lorthos',
  'Lotleth Troll',
  'Lurrus',
  // ── M ──────────────────────────────────────────────────────────────────
  'Maelstrom Wanderer',
  'Magda',
  'Mana Dork',
  'Marchesa',
  'Massacre Girl',
  'Massacre Wurm',
  'Master Biomancer',
  'Master of the Wild Hunt',
  'Mayael the Anima',
  'Meloku',
  'Merieke',
  'Medomai the Ageless',
  'Meren',
  'Metallic Mimic',
  'Mimeoplasm',
  'Mirri',
  'Mogis',
  'Monastery Mentor',
  'Mother of Runes',
  'Morophon',
  'Muldrotha',
  'Multani',
  'Murderous Rider',
  // ── N ──────────────────────────────────────────────────────────────────
  'Najeela',
  'Narset',
  'Naru Meha',
  'Nekusar',
  'Nezahal',
  'Nicol Bolas',
  'Nighthawk Scavenger',
  'Niv-Mizzet',
  'Notion Thief',
  'Nylea',
  // ── O ──────────────────────────────────────────────────────────────────
  'Ob Nixilis',
  'Obzedat',
  'Olivia Voldaren',
  'Omnath',
  'Oracle of Mul Daya',
  'Orcish Bowmasters',
  'Oketra',
  'Oviya Pashiri',
  // ── P ──────────────────────────────────────────────────────────────────
  'Phage',
  'Phenax',
  'Phyrexian Obliterator',
  'Polukranos',
  'Prime Speaker Vannifar',
  'Prime Speaker Zegana',
  'Progenitus',
  'Prossh',
  'Purphoros',
  // ── Q ──────────────────────────────────────────────────────────────────
  'Questing Beast',
  'Quicksilver Amulet',
  // ── R ──────────────────────────────────────────────────────────────────
  'Rafiq',
  'Ragavan',
  'Rankle',
  'Ravenous Chupacabra',
  'Reaper King',
  'Reclamation Sage',
  'Riku',
  'Rith the Awakener',
  'Rofellos',
  'Rograkh',
  'Rorix Bladewing',
  'Ruric Thar',
  'Rystic Study',
  // ── S ──────────────────────────────────────────────────────────────────
  'Sakashima',
  'Scion of the Ur-Dragon',
  'Seedborn Muse',
  'Selvala',
  'Serra Angel',
  'Sheoldred',
  'Shivan Dragon',
  'Sidisi',
  'Siege Rhino',
  'Sigarda',
  'Simic Sky Swallower',
  'Sliver Legion',
  'Sliver Overlord',
  'Sliver Queen',
  'Snapcaster Mage',
  'Solemn Simulacrum',
  'Sphinx of the Steel Wind',
  'Stoneforge Mystic',
  'Stormbreath Dragon',
  'Sun Titan',
  'Sundering Titan',
  'Surrak Dragonclaw',
  'Syr Gwyn',
  // ── T ──────────────────────────────────────────────────────────────────
  'Talrand',
  'Tamiyo\'s Compleation',
  'Tarmogoyf',
  'Tasigur',
  'Teferi\'s Protection',
  'Teneb the Harvester',
  'Teysa Karlov',
  'Thalia',
  'The Gitrog Monster',
  'The Scarab God',
  'The Ur-Dragon',
  'Thragtusk',
  'Thrun',
  'Thundermaw Hellkite',
  'Tireless Tracker',
  'Toski',
  'Treva',
  'Trostani',
  'True-Name Nemesis',
  // ── U ──────────────────────────────────────────────────────────────────
  'Ugin',
  'Ulamog',
  'Ulasht',
  'Urabrask',
  'Uril',
  'Urza',
  'Utvara Hellkite',
  // ── V ──────────────────────────────────────────────────────────────────
  'Vaevictis Asmadi',
  'Valduk',
  'Vampire Nighthawk',
  'Varolz',
  'Vendilion Clique',
  'Venser',
  'Verdant Force',
  'Vigor',
  'Vorel',
  'Vorinclex',
  'Vorosh',
  // ── W ──────────────────────────────────────────────────────────────────
  'Walking Ballista',
  'Wandering Archaic',
  'Whisper',
  'Wrenn and Six',
  'Wort',
  'Wurmcoil Engine',
  // ── X ──────────────────────────────────────────────────────────────────
  'Xenagos',
  'Xantcha',
  // ── Y ──────────────────────────────────────────────────────────────────
  'Yarok',
  'Yawgmoth',
  'Yisan',
  'Yosei',
  'Yuriko',
  // ── Z ──────────────────────────────────────────────────────────────────
  'Zacama',
  'Zealous Conscripts',
  'Zedruu',
  'Zirda',
  'Zurgo Helmsmasher',
  'Zur the Enchanter',
];

/**
 * Returns a random creature name from the list.
 * @returns {string} A random Magic creature name
 */
export function getRandomCreatureName() {
  return MAGIC_CREATURES[Math.floor(Math.random() * MAGIC_CREATURES.length)];
}
